version: "3.7"

services:
  gamedaybot:
    build:
      context: .
    restart: always
    environment:
      #Bot ID from the GroupMe developers page (REQUIRED IF USING GROUPME)
      # BOT_ID: "YOUR_BOT_ID_HERE"
      #Webhook URL from the Slack App page (REQUIRED IF USING SLACK)
      #SLACK_WEBHOOK_URL: "YOUR_SLACK_WEBHOOK_URL_HERE"
      #This is your Webhook URL from the Discord Settings page (REQUIRED IF USING DISCORD)
      DISCORD_WEBHOOK_URL: "YOUR_DISCORD_WEBHOOK_URL_HERE"
      #ESPN league id (REQUIRED)
      LEAGUE_ID: "YOUR_LEAGUE_ID_HERE"
      # #When the bot will start paying attention and sending messages to your chat.
      # START_DATE:
      # #When the bot will stop paying attention and stop sending messages to your chat.
      # END_DATE:
      # #ESPN League year
      LEAGUE_YEAR: "2025"
      # #The timezone that the messages will look to send in. (America/New_York by default)
      # TIMEZONE:
      #The message that the bot will say when it is started (can be blank for no message)
      # INIT_MSG: "test bot up"
      # #Your draft date in YYYY-MM-DD format to enable daily draft reminders at 9:00 AM
      # DRAFT_DATE: "2025-09-01"
      # #If set to True, when standings are posted on Wednesday it will also include top half scoring wins
      # TOP_HALF_SCORING:
      # #If set to True, when matchups are posted on Tuesday it will also include a random phrase
      # RANDOM_PHRASE:
      #Used for private leagues. See Private Leagues Section for documentation
      ESPN_S2: "YOUR_ESPN_S2_TOKEN_HERE"
      #Used for private leagues. See Private Leagues Section for documentation
      SWID: "YOUR_SWID_HERE"
      DISCORD_TOKEN: "YOUR_DISCORD_BOT_TOKEN_HERE"
      DISCORD_SERVER_ID: "YOUR_DISCORD_SERVER_ID_HERE"